spring:

  application:
    name: Task Manager
  datasource:
    url: jdbc:postgresql://task-manager-db.c5wkqwu2q57g.us-east-1.rds.amazonaws.com/postgres
    username: wera
    password: password
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: PostgresSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
